### ISSUE TITLE
Can you share the files needed for running scripts in datatransform (e.g., avazu2TF.py)

### ISSUE THREAD

**Issue by rguo12** [fuyuanlyu/OptFS#1]
Hi,

I downloaded the avazu dataset from Kaggle, but was not able to run the code avazu2TF.py due to the following error
FileNotFoundError: [Errno 2] No such file or directory: 'data/avazu/stats/feat_map.pkl'

It would be great if you can share all the data files that are not from Kaggle.

Best,

RC

**Comment by fuyuanlyu** [comment]
Hi Dr. Guo,

Thanks for your interest in our work.
I think the error is caused by missing the "--store_stat" argument when running avazu2TF.py. This argument asks the avazu2TF.py to generate the feature map first, and then create the tfrecord dataset. Here is an example:
```
python datatransform/avazu2TF.py --store_stat --stats data/avazu/stats
		--dataset RAW_DATASET_FILE --record data/avazu/tfrecord \
		--threshold 2 --ratio 0.8 0.1 0.1 \
```
Please let me know if this helps you.


Yours,
Fuyuan

**Comment by fuyuanlyu** [comment]
Feel free to drop me an email if further discussion is needed.

**Comment by rguo12** [comment]
> Hi Dr. Guo,
> 
> Thanks for your interest in our work. I think the error is caused by missing the "--store_stat" argument when running avazu2TF.py. This argument asks the avazu2TF.py to generate the feature map first, and then create the tfrecord dataset. Here is an example:
> 
> ```
> python datatransform/avazu2TF.py --store_stat --stats data/avazu/stats
> 		--dataset RAW_DATASET_FILE --record data/avazu/tfrecord \
> 		--threshold 2 --ratio 0.8 0.1 0.1 \
> ```
> 
> Please let me know if this helps you.
> 
> Yours, Fuyuan

Thank you Fuyuan, now it works!
